### Buscar todos los usuarios
GET http://localhost:3000/usuarios

### Buscar por nombre
GET http://localhost:3000/usuarios?nombre=Ana

### Buscar por edad
GET http://localhost:3000/usuarios?edad=25

### Buscar por ciudad
GET http://localhost:3000/usuarios?ciudad=Quito

### Buscar por nombre, edad y ciudad
GET http://localhost:3000/usuarios?nombre=Pedro&edad=25&ciudad=Quito